import { Role } from "@prisma/client";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import { requireRole, RbacError, rbacErrorResponse } from "@/lib/rbac";
import { writeAuditLog, sourceIpFromRequest } from "@/lib/audit";

export const runtime = "nodejs";

const ALL_ROLES = [
  Role.POLICE_OFFICER,
  Role.INVESTIGATING_OFFICER,
  Role.COURT_OFFICIAL,
  Role.FORENSIC_LAB,
  Role.ADMIN,
];

/**
 * GET /api/v1/documents/{documentId}/versions/{versionId}/certificate
 *
 * NOT in docs/04-api-spec.md — step 4 never built this endpoint, and
 * docs/01's requirement ("software cannot self-certify evidence... a
 * human still signs it") means this can only ever produce a PRE-FILLED,
 * unsigned certificate. It is never presented as valid on its own — the
 * PDF says so explicitly, with a blank signature block.
 */
export async function GET(
  req: Request,
  { params }: { params: { documentId: string; versionId: string } }
): Promise<Response> {
  let actor;
  try {
    actor = requireRole(req, ALL_ROLES);
  } catch (err) {
    if (err instanceof RbacError) return rbacErrorResponse(err);
    throw err;
  }

  const version = await prisma.documentVersion.findUnique({
    where: { id: params.versionId },
    include: { document: { include: { case: true } } },
  });
  if (!version || version.documentId !== params.documentId) {
    return Response.json({ error: "NOT_FOUND", message: "Document version not found." }, { status: 404 });
  }

  const anchor = await prisma.anchorLog.findFirst({
    where: { documentVersionId: version.id },
    orderBy: { anchoredAt: "desc" },
  });

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();

  let y = height - 60;
  const left = 50;
  const lineHeight = 18;

  const drawTitle = (text: string, size = 13) => {
    page.drawText(text, { x: left, y, size, font: bold, color: rgb(0.1, 0.1, 0.1) });
    y -= size + 10;
  };
  const drawField = (label: string, value: string) => {
    page.drawText(label, { x: left, y, size: 10, font: bold, color: rgb(0.2, 0.2, 0.2) });
    page.drawText(value, { x: left + 170, y, size: 10, font, color: rgb(0.1, 0.1, 0.1) });
    y -= lineHeight;
  };
  const drawWrapped = (text: string, size = 9) => {
    const maxWidth = width - left * 2;
    const words = text.split(" ");
    let line = "";
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(test, size) > maxWidth) {
        page.drawText(line, { x: left, y, size, font, color: rgb(0.25, 0.25, 0.25) });
        y -= size + 4;
        line = word;
      } else {
        line = test;
      }
    }
    if (line) {
      page.drawText(line, { x: left, y, size, font, color: rgb(0.25, 0.25, 0.25) });
      y -= size + 4;
    }
  };

  drawTitle("BHARATIYA SAKSHYA ADHINIYAM, 2023 — SECTION 63 CERTIFICATE", 14);
  drawTitle("(SYSTEM-GENERATED, PRE-FILLED — NOT VALID UNTIL SIGNED BELOW)", 10);
  y -= 10;

  drawField("Case Number:", version.document.case.caseNumber);
  drawField("Document Title:", version.document.title);
  drawField("Document Version:", `v${version.versionNo}`);
  drawField("Grid Size:", `${version.gridSize} x ${version.gridSize}`);
  drawField("Merkle Root (SHA-256):", version.merkleRoot);
  drawField("Client Hash (SHA-256):", version.clientHash);
  drawField("Chain Hash (SHA-256):", version.chainHash);
  drawField("Previous Hash:", version.previousHash ?? "(first version)");
  drawField("MinIO Object Lock URI:", anchor?.objectLockUri ?? "(not yet anchored)");
  drawField("Polygon Amoy Tx Hash:", anchor?.polygonTxHash ?? "(not yet anchored on-chain)");
  drawField("Anchored At:", anchor?.anchoredAt.toISOString() ?? "(not yet anchored)");
  drawField("Certificate Generated At:", new Date().toISOString());
  drawField("Generated For (role):", actor.role);
  y -= 10;

  drawWrapped(
    "This certificate has been automatically generated by DigiVault and pre-filled with the cryptographic " +
      "identity of the electronic record described above. Per Section 63 of the Bharatiya Sakshya Adhiniyam, " +
      "2023, a certificate for electronic evidence must be signed by the person having lawful control of the " +
      "device or system over which this record was produced. Software cannot self-certify evidence — a human " +
      "must review and sign this document before it has any legal effect."
  );

  y -= 30;
  page.drawLine({ start: { x: left, y }, end: { x: left + 250, y }, thickness: 1, color: rgb(0.3, 0.3, 0.3) });
  y -= 14;
  page.drawText("Signature", { x: left, y, size: 9, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 30;
  drawField("Name:", "________________________________");
  drawField("Designation:", "________________________________");
  drawField("Date:", "________________________________");

  const bytes = await pdf.save();

  await writeAuditLog({
    actorId: actor.userId,
    action: "GENERATE_CERTIFICATE",
    targetId: version.id,
    sourceIp: sourceIpFromRequest(req),
  });

  return new Response(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="bsa-certificate-${version.document.title.replace(/[^a-z0-9]+/gi, "-")}-v${version.versionNo}.pdf"`,
    },
  });
}
